### ISSUE TITLE
test configs

### ISSUE THREAD

**Issue by blugavere** [DanWahlin/Microservices-ASPNET-Core-Docker-Course#1]
it would be helpful to see a demo implementation of multi-service end to end testing using docker compose test configuration and automated db seeding

ideally a CI pipeline would start all containers, seed the dbs, start all services, and then run `npm test` and demonstrate a request bouncing around the entire ecosystem.

**Comment by DanWahlin** [comment]
Hmmm - never saw the email for this one come in, unfortunately. Sorry about that. It'd be great to have that functionality but it's not something I'm going to be able to do right now. Happy to take a pull request though if you end up digging into that aspect more.
